# Generated by Django 3.1.7 on 2021-03-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210322_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
    ]
